# language: node_js

# node_js:
#   - "8.12"

# services:
#   - mongodb
#   - redis-server

# before_install:
#   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
#   - export PATH="$HOME/.yarn/bin:$PATH"

# cache: yarn
